apple:
  certs:
    dir: "${CERT_DIR:config/certificates/applepay}"
    merchant-id: "merchant_id.pem"
    payment-processing: "apple_pay.pem"
  merchant:
    id: "your.merchant.id"
    domain: "yourdomain.com"
    display-name: "Your Store Name"
  